/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/academic-years/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Учебные периоды для селектора семестра (кэш 2 часа). */
        get: operations["v1_academic_years_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Достижения (заявки студентов).
         *
         *     - create — загрузка достижения студентом (throttle 'upload');
         *     - retrieve — карточка заявки (владелец или сотрудник в scope);
         *     - partial_update / destroy — правка/удаление своей заявки
         *       (чужие скрыты фильтром по владельцу: 404, существование не раскрывается);
         *     - list — заявки на модерацию для сотрудника (?list_type=pending|reviewed),
         *       в пагинированный ответ добавляются stats и top5;
         *     - review — решение по заявке (кафедра / декан / ректорат);
         *     - config — конфигурация формы загрузки (кэш 1 час).
         */
        get: operations["v1_achievements_list"];
        put?: never;
        /**
         * @description Достижения (заявки студентов).
         *
         *     - create — загрузка достижения студентом (throttle 'upload');
         *     - retrieve — карточка заявки (владелец или сотрудник в scope);
         *     - partial_update / destroy — правка/удаление своей заявки
         *       (чужие скрыты фильтром по владельцу: 404, существование не раскрывается);
         *     - list — заявки на модерацию для сотрудника (?list_type=pending|reviewed),
         *       в пагинированный ответ добавляются stats и top5;
         *     - review — решение по заявке (кафедра / декан / ректорат);
         *     - config — конфигурация формы загрузки (кэш 1 час).
         */
        post: operations["v1_achievements_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievements/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Достижения (заявки студентов).
         *
         *     - create — загрузка достижения студентом (throttle 'upload');
         *     - retrieve — карточка заявки (владелец или сотрудник в scope);
         *     - partial_update / destroy — правка/удаление своей заявки
         *       (чужие скрыты фильтром по владельцу: 404, существование не раскрывается);
         *     - list — заявки на модерацию для сотрудника (?list_type=pending|reviewed),
         *       в пагинированный ответ добавляются stats и top5;
         *     - review — решение по заявке (кафедра / декан / ректорат);
         *     - config — конфигурация формы загрузки (кэш 1 час).
         */
        get: operations["v1_achievements_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description Достижения (заявки студентов).
         *
         *     - create — загрузка достижения студентом (throttle 'upload');
         *     - retrieve — карточка заявки (владелец или сотрудник в scope);
         *     - partial_update / destroy — правка/удаление своей заявки
         *       (чужие скрыты фильтром по владельцу: 404, существование не раскрывается);
         *     - list — заявки на модерацию для сотрудника (?list_type=pending|reviewed),
         *       в пагинированный ответ добавляются stats и top5;
         *     - review — решение по заявке (кафедра / декан / ректорат);
         *     - config — конфигурация формы загрузки (кэш 1 час).
         */
        delete: operations["v1_achievements_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Достижения (заявки студентов).
         *
         *     - create — загрузка достижения студентом (throttle 'upload');
         *     - retrieve — карточка заявки (владелец или сотрудник в scope);
         *     - partial_update / destroy — правка/удаление своей заявки
         *       (чужие скрыты фильтром по владельцу: 404, существование не раскрывается);
         *     - list — заявки на модерацию для сотрудника (?list_type=pending|reviewed),
         *       в пагинированный ответ добавляются stats и top5;
         *     - review — решение по заявке (кафедра / декан / ректорат);
         *     - config — конфигурация формы загрузки (кэш 1 час).
         */
        patch: operations["v1_achievements_partial_update"];
        trace?: never;
    };
    "/api/v1/achievements/{id}/review/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Достижения (заявки студентов).
         *
         *     - create — загрузка достижения студентом (throttle 'upload');
         *     - retrieve — карточка заявки (владелец или сотрудник в scope);
         *     - partial_update / destroy — правка/удаление своей заявки
         *       (чужие скрыты фильтром по владельцу: 404, существование не раскрывается);
         *     - list — заявки на модерацию для сотрудника (?list_type=pending|reviewed),
         *       в пагинированный ответ добавляются stats и top5;
         *     - review — решение по заявке (кафедра / декан / ректорат);
         *     - config — конфигурация формы загрузки (кэш 1 час).
         */
        post: operations["v1_achievements_review_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/achievements/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Конфигурация формы достижения: категории, подтипы, уровни, результаты, правила баллов. */
        get: operations["v1_achievements_config_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Аутентификация: login / logout / session (ex check-auth) / forgot-password.
         *
         *     Регистрация отключена намеренно (см. RegistrationAPIView — код сохранён,
         *     маршрут не подключён).
         */
        post: operations["v1_auth_forgot_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Аутентификация: login / logout / session (ex check-auth) / forgot-password.
         *
         *     Регистрация отключена намеренно (см. RegistrationAPIView — код сохранён,
         *     маршрут не подключён).
         */
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Аутентификация: login / logout / session (ex check-auth) / forgot-password.
         *
         *     Регистрация отключена намеренно (см. RegistrationAPIView — код сохранён,
         *     маршрут не подключён).
         */
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Текущая сессия: данные пользователя либо {"isAuthenticated": false}. */
        get: operations["v1_auth_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Справочник категорий достижений с подтипами (кэш 2 часа). */
        get: operations["v1_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-files/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Скачать файл документа
         * @description Потоковое проксирование файла из хранилища (Content-Disposition: attachment).
         */
        get: operations["v1_document_files_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-files/{id}/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Предпросмотр файла документа (офисные форматы — в PDF)
         * @description Отдаёт файл inline; .doc/.docx конвертируются в PDF (Gotenberg) с кэшем.
         */
        get: operations["v1_document_files_preview_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Учебные группы, доступные сотруднику (в его scope, только с студентами).
         *     Кэш 5 минут, per-cookie (данные зависят от роли).
         */
        get: operations["v1_groups_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/pending-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Число заявок, ожидающих действия текущего сотрудника (0 для не-сотрудников). */
        get: operations["v1_notifications_pending_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rating/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Рейтинг студентов, всегда текущий семестр. Доступ только сотрудникам:
         *     ФИО и баллы всех студентов - не для любого авторизованного.
         *
         *     - list — пагинированный рейтинг с фильтрами и сортировкой по категории;
         *     - filters — данные для построения фильтров (кэш 2 часа);
         *     - export — выгрузка рейтинга в Excel.
         */
        get: operations["v1_rating_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rating/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Экспорт рейтинга в Excel
         * @description Рейтинг студентов, всегда текущий семестр. Доступ только сотрудникам:
         *     ФИО и баллы всех студентов - не для любого авторизованного.
         *
         *     - list — пагинированный рейтинг с фильтрами и сортировкой по категории;
         *     - filters — данные для построения фильтров (кэш 2 часа);
         *     - export — выгрузка рейтинга в Excel.
         */
        get: operations["v1_rating_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rating/filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Рейтинг студентов, всегда текущий семестр. Доступ только сотрудникам:
         *     ФИО и баллы всех студентов - не для любого авторизованного.
         *
         *     - list — пагинированный рейтинг с фильтрами и сортировкой по категории;
         *     - filters — данные для построения фильтров (кэш 2 часа);
         *     - export — выгрузка рейтинга в Excel.
         */
        get: operations["v1_rating_filters_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rejection-reasons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Справочник активных причин отклонения заявок (кэш 2 часа). */
        get: operations["v1_rejection_reasons_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Профиль сотрудника (деканат / кафедра / ректорат). */
        get: operations["v1_staff_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Студенты.
         *
         *     - list — студенты в области видимости сотрудника с фильтрами и выбором
         *       семестра (прошлый семестр — баллы из истории SemesterScore);
         *     - retrieve — полный профиль (свой или в scope сотрудника);
         *     - me — собственный профиль студента.
         */
        get: operations["v1_students_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Студенты.
         *
         *     - list — студенты в области видимости сотрудника с фильтрами и выбором
         *       семестра (прошлый семестр — баллы из истории SemesterScore);
         *     - retrieve — полный профиль (свой или в scope сотрудника);
         *     - me — собственный профиль студента.
         */
        get: operations["v1_students_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/students/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Студенты.
         *
         *     - list — студенты в области видимости сотрудника с фильтрами и выбором
         *       семестра (прошлый семестр — баллы из истории SemesterScore);
         *     - retrieve — полный профиль (свой или в scope сотрудника);
         *     - me — собственный профиль студента.
         */
        get: operations["v1_students_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Сериализатор для . */
        AcademicYear: {
            readonly id: number;
            /** Название периода */
            label: string;
            /**
             * Дата начала
             * Format: date
             */
            start_date: string;
            /**
             * Дата окончания
             * Format: date
             */
            end_date: string;
            /** Текущий семестр */
            is_current?: boolean;
        };
        AchievementConfig: {
            readonly structure: {
                [key: string]: unknown;
            };
            readonly levels: components["schemas"]["Level"][];
            readonly results: components["schemas"]["AchievementResult"][];
            readonly doc_types: components["schemas"]["DocType"][];
        };
        AchievementResult: {
            /** Код */
            code: string;
            /** Название */
            label: string;
        };
        AchievementType: {
            /** Код */
            code: string;
            /** Название */
            label: string;
            /** Требует указания уровня */
            needs_level?: boolean;
            /** Требует указания результата */
            needs_result?: boolean;
            readonly allowed_results: string[];
        };
        AchievementUpload: {
            record_book: string;
            /** Код */
            category: string;
            sub_type: string;
            /** Код */
            level?: string | null;
            /** Код */
            result?: string | null;
            achievement: string;
            /** Format: date */
            date_received?: string;
            /**
             * Код
             * @default other
             */
            doc_type: string;
            files: string[];
        };
        /**
         * @description * `approve` - approve
         *     * `reject` - reject
         * @enum {string}
         */
        ActionEnum: "approve" | "reject";
        Category: {
            /** Код */
            code: string;
            /** Название */
            label: string;
            readonly sub_types: components["schemas"]["AchievementType"][];
        };
        DocType: {
            /** Код */
            code: string;
            /** Название */
            label: string;
        };
        Document: {
            readonly id: number;
            /** Категория */
            category: number;
            readonly category_display: string;
            /** Подтип */
            sub_type: number;
            readonly sub_type_display: string;
            /** Уровень */
            level?: number | null;
            readonly level_display: string;
            /** Результат */
            result?: number | null;
            readonly result_display: string;
            /** Название достижения */
            achievement: string;
            /** Причина отказа */
            rejection_reason?: string | null;
            /** Баллы */
            score?: number;
            /** Статус */
            status: number;
            readonly status_display: string;
            /** Тип документа */
            doc_type: number;
            readonly doc_type_display: string;
            readonly files: components["schemas"]["DocumentFile"][];
            /**
             * Дата получения
             * Format: date
             */
            date_received?: string;
            /** Format: date-time */
            readonly uploaded_at: string;
        };
        DocumentFile: {
            readonly id: number;
            /** Оригинальное имя файла */
            original_file_name?: string;
            /**
             * Дата загрузки
             * Format: date-time
             */
            readonly uploaded_at: string;
            /**
             * Порядок
             * @description Для сортировки файлов
             */
            order?: number;
            /** Документ */
            document: number;
        };
        /** @description Единый формат ошибки API: {"detail": "..."}. */
        ErrorDetail: {
            detail: string;
        };
        /** @description Сериализатор для фильтрации факультетов. */
        FacultyFilter: {
            readonly id: number;
            /** Сокращение */
            short_name: string;
            /** Название факультета */
            name: string;
        };
        ForgotPasswordRequest: {
            /**
             * Format: email
             * @description Введите ваш email для восстановления пароля
             */
            email: string;
        };
        /** @description Сериализатор для групп. */
        Group: {
            readonly id: number;
            /** Название группы */
            name: string;
            /** Курс */
            course: number;
            readonly faculty_name: string;
            /** Учебный год */
            academic_year: string;
            /** Уровень */
            education_level: string;
            /** Форма обучения */
            education_form: string;
            readonly specialty_name: string;
            readonly specialty_code: string;
        };
        /** @description Сериализатор для фильтрации групп. */
        GroupFilter: {
            readonly id: number;
            /** Название группы */
            name: string;
            /** Курс */
            course: number;
            readonly faculty_id: number;
            readonly faculty_name: string;
            /** Учебный год */
            academic_year: string;
        };
        Level: {
            /** Код */
            code: string;
            /** Название */
            label: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        /** @description Успешный ответ вида {"message": "..."}. */
        Message: {
            message: string;
        };
        PaginatedPendingDocumentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PendingDocument"][];
        };
        PaginatedStudentProfileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudentProfile"][];
        };
        PaginatedStudentRatingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StudentRating"][];
        };
        /**
         * @description Частичное редактирование достижения студентом (PATCH).
         *
         *     Все поля опциональны. Подтип проверяется в рамках категории (переданной или
         *     текущей). Если переданы файлы — старые удаляются и заменяются новыми.
         *     Балл пересчитывается в `Document.save()`. Если документ был отклонён, при
         *     сохранении он возвращается на повторное рассмотрение (статус 'pending').
         *
         *     Редактирование уже подтверждённых достижений запрещается на уровне view.
         */
        PatchedAchievementUpdate: {
            /** Код */
            category?: string;
            sub_type?: string;
            /** Код */
            level?: string | null;
            /** Код */
            result?: string | null;
            achievement?: string;
            /** Format: date */
            date_received?: string;
            /** Код */
            doc_type?: string;
            files?: string[];
        };
        PendingCount: {
            readonly pending_docs_count: number;
        };
        PendingDocument: {
            readonly id: number;
            /** Категория */
            category: number;
            readonly category_display: string;
            /** Подтип */
            sub_type: number;
            readonly sub_type_display: string;
            /** Уровень */
            level?: number | null;
            readonly level_display: string;
            /** Результат */
            result?: number | null;
            readonly result_display: string;
            /** Название достижения */
            achievement: string;
            /** Причина отказа */
            rejection_reason?: string | null;
            /** Баллы */
            score?: number;
            /** Статус */
            status: number;
            readonly status_display: string;
            /** Тип документа */
            doc_type: number;
            readonly doc_type_display: string;
            readonly files: components["schemas"]["DocumentFile"][];
            /**
             * Дата получения
             * Format: date
             */
            date_received?: string;
            /** Format: date-time */
            readonly uploaded_at: string;
            readonly user_id: number;
            readonly student_id: number;
            readonly student_name: string;
            /** @default Без группы */
            readonly group: string;
            readonly group_id: number;
            readonly course: number;
            /** @default — */
            readonly faculty: string;
            /** @default — */
            readonly record_book: string;
        };
        /** @description Сериализатор фильтра рейтинга для модерации документа. */
        RatingFiltersResponse: {
            readonly faculties: components["schemas"]["FacultyFilter"][];
            readonly courses: number[];
            readonly groups: components["schemas"]["GroupFilter"][];
        };
        /** @description Сериализатор причин отклонения заявок. */
        RejectionReason: {
            readonly id: number;
            /** Текст причины */
            text: string;
        };
        /** @description Сериализатор для модерации документа. */
        ReviewDocumentRequest: {
            action: components["schemas"]["ActionEnum"];
            /** @description Список причин при отклонении */
            reasons?: string[];
        };
        /** @description Сериализатор ответа при модерации документа. */
        ReviewDocumentResponse: {
            message: string;
        };
        /** @description Строка истории баллов студента за один семестр. */
        SemesterScore: {
            readonly semester_id: number;
            readonly semester_label: string;
            readonly is_current: boolean;
            /** Format: date */
            readonly start_date: string;
            /** Format: date */
            readonly end_date: string;
            readonly total_score: number;
            academic_score?: number;
            research_score?: number;
            sport_score?: number;
            social_score?: number;
            cultural_score?: number;
        };
        /** @description Сериализатор ответа профиля сотрудника. */
        StaffProfileResponse: {
            id: number;
            full_name: string;
            /** Format: email */
            email: string;
            phone: string | null;
            department_name: string;
            faculty_name: string;
            roles: string[];
            is_own_profile: boolean;
            is_staff: boolean;
            type: string;
        };
        StudentProfile: {
            readonly id: number;
            readonly user_id: number | null;
            /**
             * ФИО
             * @description Полное ФИО студента
             */
            full_name: string;
            readonly short_name: string;
            /** Format: email */
            email?: string | null;
            /** Зачетка */
            record_book?: string | null;
            /** @default Без группы */
            readonly group: string;
            readonly group_id: number;
            readonly course: number;
            /** @default — */
            readonly faculty: string;
            /**
             * Статус
             * @description Код статуса
             */
            status?: string;
            /**
             * Расшифровка Статуса
             * @description Расшифровка кода статуса
             */
            status_decoding?: string;
            /**
             * В архиве с
             * Format: date-time
             * @description Если заполнено - студент архивирован: скрыт из текущего рейтинга/списков/дашборда, но запись, история баллов и файлы сохранены. Проставляется при импорте для статусов отчислен/окончил/архив или для студентов, пропавших из полной выгрузки.
             */
            archived_at?: string | null;
            readonly is_archived: boolean;
            academic_score?: number;
            research_score?: number;
            sport_score?: number;
            social_score?: number;
            cultural_score?: number;
            readonly total_score: number;
            readonly documents: components["schemas"]["Document"][];
            readonly semester_history: components["schemas"]["SemesterScore"][];
        };
        /** @description Строка публичного рейтинга: живые баллы текущего семестра из кэша Student. */
        StudentRating: {
            readonly id: number;
            readonly user_id: number | null;
            /**
             * ФИО
             * @description Полное ФИО студента
             */
            full_name: string;
            readonly short_name: string;
            /** @default Без группы */
            readonly group: string;
            readonly group_id: number;
            /** @default 0 */
            readonly course: number;
            /** @default — */
            readonly faculty: string;
            readonly total_score: number;
            academic_score?: number;
            research_score?: number;
            sport_score?: number;
            social_score?: number;
            cultural_score?: number;
            /** @default 0 */
            readonly faculty_id: number;
        };
        UserResponse: {
            readonly id: number;
            /**
             * Имя пользователя
             * @description Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
             */
            username: string;
            /** @default — */
            readonly record_book: string;
            /** @default true */
            isAuthenticated: boolean;
            /**
             * Статус персонала
             * @description Отметьте, если пользователь может входить в административную часть сайта.
             */
            is_staff?: boolean;
            readonly full_name: string;
            readonly short_name: string;
            readonly roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_academic_years_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcademicYear"][];
                };
            };
        };
    };
    v1_achievements_list: {
        parameters: {
            query?: {
                /** @description ID семестра (по умолчанию — текущий) */
                academic_year?: number;
                course?: string;
                faculty_id?: string;
                group_id?: string;
                /** @description pending (по умолчанию) | reviewed */
                list_type?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description Синоним academic_year */
                semester?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPendingDocumentList"];
                };
            };
        };
    };
    v1_achievements_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID попытки отправки: повтор с тем же ключом получает 409 вместо дубля. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AchievementUpload"];
                "application/x-www-form-urlencoded": components["schemas"]["AchievementUpload"];
                "application/json": components["schemas"]["AchievementUpload"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_achievements_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingDocument"];
                };
            };
        };
    };
    v1_achievements_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_achievements_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedAchievementUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAchievementUpdate"];
                "application/json": components["schemas"]["PatchedAchievementUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_achievements_review_create: {
        parameters: {
            query?: never;
            header?: {
                /** @description UUID попытки отправки: повтор с тем же ключом получает 409 вместо дубля. */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ReviewDocumentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ReviewDocumentRequest"];
                "application/json": components["schemas"]["ReviewDocumentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDocumentResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_achievements_config_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementConfig"];
                };
            };
        };
    };
    v1_auth_forgot_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ForgotPasswordRequest"];
                "multipart/form-data": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    v1_auth_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    v1_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    v1_document_files_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_document_files_preview_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_groups_list: {
        parameters: {
            query?: {
                course?: string;
                faculty_id?: string;
                group_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    v1_notifications_pending_count_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingCount"];
                };
            };
        };
    };
    v1_rating_list: {
        parameters: {
            query?: {
                /** @description Категория сортировки: common (по умолчанию) | academic | research | sport | social | cultural */
                category?: string;
                course?: string;
                faculty_id?: string;
                group_id?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudentRatingList"];
                };
            };
        };
    };
    v1_rating_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    v1_rating_filters_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingFiltersResponse"];
                };
            };
        };
    };
    v1_rejection_reasons_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectionReason"][];
                };
            };
        };
    };
    v1_staff_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffProfileResponse"];
                };
            };
        };
    };
    v1_students_list: {
        parameters: {
            query?: {
                /** @description ID семестра (по умолчанию — текущий) */
                academic_year?: number;
                course?: string;
                faculty_id?: string;
                group_id?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /** @description Синоним academic_year */
                semester?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStudentProfileList"];
                };
            };
        };
    };
    v1_students_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentProfile"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    v1_students_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentProfile"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
}
