"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
// Дополнено вручную: сканер регистрирует только имена, у которых в разметке есть
// обёртка <Skeleton>. Таблицы (rating/my-group) скелетоном boneyard больше не
// пользуются - у них свои строки-заглушки прямо в tbody, кости удалены. Оставшиеся
// три имени добавлены вручную; после полного скана проверить, что они на месте.
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _achievement_item from './achievement-item.bones.json'
import _student_profile from './student-profile.bones.json'
import _upload_form_fields from './upload-form-fields.bones.json'

configureBoneyard({"color":"#e5e5e5","animate":"shimmer"})

registerBones({
  "achievement-item": _achievement_item,
  "student-profile": _student_profile,
  "upload-form-fields": _upload_form_fields,
})
