# Generated by Django 6.0.2 on 2026-04-22 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Код факультета из БД вуза', max_length=50, unique=True, verbose_name='Код факультета')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название факультета')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Сокращение')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Псевдоним')),
                ('dean_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Декан')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('subdivision_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Институт/Филиал/Подразделение')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='Текст причины')),
                ('is_active', models.BooleanField(default=True, help_text='Если снять галочку, причина не будет предлагаться при новых отказах', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Причина отказа',
                'verbose_name_plural': 'Причины отказа',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название периода')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий семестр')),
            ],
            options={
                'verbose_name': 'Учебный период',
                'verbose_name_plural': 'Учебные периоды',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='university__start_d_765e62_idx'), models.Index(fields=['is_current'], name='university__is_curr_a2ae69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Код кафедры из БД вуза', max_length=50, unique=True, verbose_name='Код кафедры')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название кафедры')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Сокращение')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('head_name', models.CharField(blank=True, max_length=255, verbose_name='Зав. кафедрой')),
                ('status', models.PositiveIntegerField(default=0, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university_structure.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Код специальности из БД вуза', max_length=50, unique=True, verbose_name='Код специальности')),
                ('code_fgos', models.CharField(max_length=20, verbose_name='Код по ФГОС')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое название')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квалификация')),
                ('specialty_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Префикс')),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='КодРодителя')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Код группы из БД вуза', max_length=50, unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('education_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Срок обучения')),
                ('education_level', models.CharField(max_length=5, verbose_name='Уровень')),
                ('education_level_decode', models.CharField(max_length=100, verbose_name='Название уровеня')),
                ('education_form', models.CharField(max_length=5, verbose_name='Форма обучения')),
                ('education_form_decode', models.CharField(max_length=100, verbose_name='Название формы обучения')),
                ('status', models.PositiveIntegerField(default=0, null=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university_structure.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='university_structure.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='university_structure.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
