# Generated by Django 6.0.2 on 2026-03-13 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='Код факультета')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название факультета')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Сокращение')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='Псевдоним')),
                ('dean_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Декан')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('subdivision_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Институт/Филиал/Подразделение')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='Код кафедры')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название кафедры')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Сокращение')),
                ('head_name', models.CharField(blank=True, max_length=255, verbose_name='Зав. кафедрой')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='university_structure.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='Код специальности')),
                ('code_fgos', models.CharField(max_length=20, verbose_name='Код по ФГОС')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое название')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квалификация')),
                ('specialty_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Префикс')),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='КодРодителя')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Учебный год')),
                ('education_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Срок обучения')),
                ('education_level', models.CharField(max_length=100, verbose_name='Уровень')),
                ('education_form', models.CharField(max_length=100, verbose_name='Форма обучения')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university_structure.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='university_structure.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='university_structure.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
