# Generated by Django 6.0.2 on 2026-07-01 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'name'], name='university__course_f105cf_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['academic_year'], name='university__academi_d0a0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department', 'faculty'], name='university__departm_5727f4_idx'),
        ),
    ]
