# Generated by Django 6.0.2 on 2026-04-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
