# Generated by Django 6.0.2 on 2026-03-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_structure', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='education_form_name',
            new_name='education_form_decode',
        ),
    ]
