"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import quote as _url_quote
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Единый каталог для данных, которые нужно расшаривать с ПК работника ОИ
# (логи, бэкапы, дампы, пароли импорта студентов). В контейнерах монтируется как /shared.
SHARED_DIR = Path(os.getenv('SHARED_DIR', '/shared'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable must be set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

def _env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError("DJANGO_ALLOWED_HOSTS must be set in production")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'storages',
    'drf_spectacular',
    'users',
    'students',
    'university_structure',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ApiNoStoreMiddleware',
]

CORS_ALLOWED_ORIGINS = _env_list("DJANGO_CORS_ALLOWED_ORIGINS")

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

EXTERNAL_SITE_URL = os.getenv('CLIENT_URL', '')
API_SCHEMA_URL = os.getenv('API_SCHEMA_URL', '')

# Базовый URL публичного API ЭОС для синхронизации справочников
EOS_BASE_URL = os.getenv('EOS_BASE_URL', 'https://eos.bgitu.ru/api')
# Токен авторизации ЭОС для ЗАКРЫТЫХ ручек (напр. список студентов). Пусто = только публичные.
EOS_AUTH_TOKEN = os.getenv('EOS_AUTH_TOKEN', '')
CORS_ALLOW_CREDENTIALS = True
# CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True').lower() == 'true'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True').lower() == 'true'
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_COOKIE_HTTPONLY = os.getenv('CSRF_COOKIE_HTTPONLY', 'False').lower() == 'true'
SESSION_COOKIE_HTTPONLY = os.getenv('SESSION_COOKIE_HTTPONLY', 'True').lower() == 'true'

# Срок сессии 12 часов. Активность продлевает сессию.
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', 60 * 60 * 12))
SESSION_SAVE_EVERY_REQUEST = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = os.getenv('DJANGO_USE_X_FORWARDED_HOST', 'True').lower() == 'true'

# запрет mime-sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True
# ограничение утечки реферера.
SECURE_REFERRER_POLICY = 'same-origin'
# принудительный редирект на https
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True').lower() == 'true'
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True').lower() == 'true'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Единый формат ошибок: {"detail": ...} (+ Retry-After для PreviewBusy).
    'EXCEPTION_HANDLER': 'core.exceptions.api_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_RATES': {
        'login': os.getenv('THROTTLE_LOGIN', '5/min'),
        'register': os.getenv('THROTTLE_REGISTER', '60/hour'),
        'upload': os.getenv('THROTTLE_UPLOAD', '60/hour'),
        'forgot_password': os.getenv('THROTTLE_FORGOT_PASSWORD', '5/hour'),
        'preview': os.getenv('THROTTLE_PREVIEW', '120/hour'),
    },
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
# ASGI_APPLICATION = 'backend.asgi.application'
# GUNICORN_WORKER_CLASS = 'uvicorn.workers.UvicornWorker'
GUNICORN_WORKERS = int(os.getenv('GUNICORN_WORKERS', 4))
GUNICORN_TIMEOUT = int(os.getenv('GUNICORN_TIMEOUT', 120))

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
        'OPTIONS': {
            'sslmode': os.getenv('SSL_MODE', 'require'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Кэширование (Redis) 
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f"redis://{os.getenv('REDIS_HOST')}:{os.getenv('REDIS_PORT')}/0",
        'OPTIONS': {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": f"{os.getenv('REDIS_PASSWORD')}"
        },
        'TIMEOUT': 300,
    }
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Portfolio.bgitu.ru API',
    'DESCRIPTION': 'For Admin only. Schema of portfolio.bgitu.ru API. For more information, please refer to our API documentation',
    'VERSION': '1.2.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],
    'SERVE_INCLUDE_SCHEMA': True,
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# logging.FileHandler не создаёт директорию сам - гарантируем её наличие.
(SHARED_DIR / 'logs').mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Ротация вместо бесконечного роста файла: 10 МБ × 5 копий.
        'file': {
            'level': os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': SHARED_DIR / 'logs' / 'django.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        # Аудит-события (входы/выходы, решения по заявкам) - отдельный файл.
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': SHARED_DIR / 'logs' / 'audit.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['file'],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    'loggers': {
        'audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Celery
_REDIS_PW = _url_quote(os.getenv('REDIS_PASSWORD', ''), safe='')
CELERY_BROKER_URL = f"redis://:{_REDIS_PW}@{os.getenv('REDIS_HOST')}:{os.getenv('REDIS_PORT')}/1"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Минимизация ресурсов: пока один процесс, без набора очереди впрок. + лимиты времени от зависаний.
CELERY_WORKER_CONCURRENCY = 1
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 25
CELERY_TASK_TIME_LIMIT = 60 * 30

BACKUPS_DIR = os.getenv('BACKUPS_DIR', str(SHARED_DIR / 'backups'))
BACKUP_KEEP = int(os.getenv('BACKUP_KEEP', 3))

CELERY_BEAT_SCHEDULE = {
    'backup-all-daily': {
        'task': 'core.tasks.backup_all',
        # Пример из документации: crontab(minute='*/10',hour='3,17,22', day_of_week='thu,fri')
        # То есть: Execute every ten minutes, but only between 3-4 am, 5-6 pm, and 10-11 pm on Thursdays or Fridays.
        # У нас по умолчанию в 3:00 по МСК
        'schedule': crontab(hour=int(os.getenv('SCHEDULE_HOUR', 3)), minute=int(os.getenv('SCHEDULE_MINUTE', 0))),
    },
    # Ежедневная проверка: если текущий семестр закончился - авто-ролловер на следующий.
    'auto-semester-rollover-daily': {
        'task': 'students.tasks.auto_rollover_semester',
        'schedule': crontab(hour=int(os.getenv('ROLLOVER_HOUR', 4)), minute=int(os.getenv('ROLLOVER_MINUTE', 30))),
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'
CONFIG_FILE_ROOT = os.path.join(BASE_DIR, 'config-files')
# Пароли и данные для листочков со студентами пишем в общий каталог /shared/import_passwords.
IMPORT_PASSWORDS_DIR = os.getenv('IMPORT_PASSWORDS_DIR', str(SHARED_DIR / 'import_passwords'))

AUTH_USER_MODEL = 'users.User'

SCORING_CONFIG_PATH = os.path.join(CONFIG_FILE_ROOT, 'scoring_json/' ,'scoring_config.json')

AWS_ACCESS_KEY_ID = os.getenv('SEAWEEDFS_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = os.getenv('SEAWEEDFS_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('SEAWEEDFS_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('SEAWEEDFS_ENDPOINT_URL')
AWS_S3_FILE_OVERWRITE = os.getenv('SEAWEEDFS_S3_FILE_OVERWRITE', 'False').lower() == 'true'
AWS_DEFAULT_ACL = os.getenv('SEAWEEDFS_DEFAULT_ACL', 'private')
# Проверка TLS-сертификата хранилища включена по умолчанию: отключать её
# можно только осознанно через env (например, self-signed серт в локальном dev).
AWS_S3_VERIFY = os.getenv('SEAWEEDFS_S3_VERIFY', 'True').lower() == 'true'
AWS_QUERYSTRING_AUTH = os.getenv('SEAWEEDFS_QUERYSTRING_AUTH', 'True').lower() == 'true'
AWS_QUERYSTRING_EXPIRE = int(os.getenv('SEAWEEDFS_QUERYSTRING_EXPIRE', 300))

# Email settings


EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend') # Временно консольный бэкенд для тестирования
# EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'  # Правильный бэкенд для прода
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))                                    # 587 для TLS, 465 для SSL
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'              # True если используем порт 587
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() == 'true'             # True если используем порт 465
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')    # Пароль приложения
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)         # Стандартный адрес отправителя


# Предпросмотр документов (конвертация офисных файлов в PDF)
# Gotenberg - sidecar над LibreOffice; конвертация изолирована от backend.
GOTENBERG_URL = os.getenv('GOTENBERG_URL', 'http://gotenberg:3000')
GOTENBERG_TIMEOUT = int(os.getenv('GOTENBERG_TIMEOUT', 100))
# Префикс в основном бакете под кэш конвертированных PDF (TTL через lifecycle).
PREVIEW_CACHE_PREFIX = os.getenv('PREVIEW_CACHE_PREFIX', 'preview-cache')
PREVIEW_CACHE_TTL_DAYS = int(os.getenv('PREVIEW_CACHE_TTL_DAYS', 7))
# Потолок одновременных конвертаций на стороне backend (Redis-семафор).
PREVIEW_MAX_CONCURRENCY = int(os.getenv('PREVIEW_MAX_CONCURRENCY', 2))