# Generated by Django 6.0.2 on 2026-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('academic', 'Учебная'), ('cultural', 'Культурно-творческая'), ('social', 'Общественная'), ('sport', 'Спортивная'), ('research', 'Научно-исследовательская')], max_length=255)),
                ('sub_type', models.CharField(choices=[('grades', 'Успеваемость'), ('olympiad', 'Олимпиада / Конкурс'), ('education', 'Доп. обр. программа'), ('contest', 'Научный конкурс'), ('publication', 'Публикация'), ('conference', 'Доклад на конференции'), ('msmk', 'Мастер спорта межд. класса'), ('team_russia', 'Член сборной России'), ('competition', 'Спортивное соревнование'), ('promotion', 'Популяризация спорта'), ('elder', 'Староста'), ('union', 'Профсоюз / Студсовет'), ('volunteer', 'Волонтерская деятельность'), ('career', 'Профориентация / Лагеря')], default='other', max_length=255, verbose_name='Подтип')),
                ('level', models.CharField(choices=[('world', 'Международный (Мир)'), ('international', 'Международный'), ('russian', 'Всероссийский / РФ'), ('cfo', 'Окружной (ЦФО)'), ('regional', 'Областной / Региональный'), ('university', 'Вузовский'), ('none', 'Не применимо')], default='none', max_length=255, verbose_name='Уровень')),
                ('result', models.CharField(choices=[('1', '1 место / Победитель'), ('2', '2 место / Призер'), ('3', '3 место / Призер'), ('excellent', 'Только "отлично"'), ('good_excellent', '«Хорошо» и «отлично»'), ('vak_rinc', 'ВАК / РИНЦ'), ('other', 'Прочие'), ('none', 'Не применимо')], default='other', max_length=255, verbose_name='Результат')),
                ('achievement', models.CharField(max_length=255, verbose_name='Название достижения')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('doc_type', models.CharField(choices=[('diploma', 'Диплом'), ('certificate', 'Сертификат'), ('certificate_of_participation', 'Свидетельство об участии'), ('letter_of_thanks', 'Благодарственное письмо'), ('other', 'Другое')], default='other', max_length=255)),
                ('original_file_name', models.CharField(default='NO_FILENAME', max_length=255)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('record_book', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('academic_score', models.PositiveIntegerField(default=0)),
                ('research_score', models.PositiveIntegerField(default=0)),
                ('sport_score', models.PositiveIntegerField(default=0)),
                ('social_score', models.PositiveIntegerField(default=0)),
                ('cultural_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профиль студента',
                'verbose_name_plural': 'Профили студентов',
            },
        ),
    ]
