# Generated by Django 6.0.2 on 2026-07-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('university_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Учебный период, к которому относится заявка (проставляется при создании).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='university_structure.academicyear', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='document',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.achievementtype', verbose_name='Подтип'),
        ),
    ]
