# Generated by Django 6.0.2 on 2026-03-10 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='sub_type',
            field=models.CharField(choices=[('olympiad', 'Олимпиада / Конкурс'), ('msmk', 'Мастер спорта межд. класса'), ('contest', 'Научный конкурс'), ('publication', 'Публикация'), ('volunteer', 'Волонтерская деятельность'), ('competition', 'Спортивное соревнование'), ('career', 'Профориентация / Лагеря'), ('union', 'Профсоюз / Студсовет'), ('education', 'Доп. обр. программа'), ('conference', 'Доклад на конференции'), ('promotion', 'Популяризация спорта'), ('grades', 'Успеваемость'), ('team_russia', 'Член сборной России'), ('contest', 'Конкурс / Фестиваль'), ('elder', 'Староста')], default='other', max_length=50, verbose_name='Подтип'),
        ),
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код')),
                ('label', models.CharField(max_length=100, verbose_name='Название')),
                ('needs_level', models.BooleanField(default=False, verbose_name='Требует указания уровня')),
                ('needs_result', models.BooleanField(default=False, verbose_name='Требует указания результата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='students.category')),
            ],
            options={
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Уровень (eng)')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='Результат (eng)')),
                ('score', models.IntegerField(verbose_name='Количество баллов')),
                ('achievement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='students.achievementtype')),
            ],
        ),
    ]
