# Generated by Django 6.0.2 on 2026-04-08 19:15

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('academic_score'), '+', models.F('research_score')), '+', models.F('sport_score')), '+', models.F('social_score')), '+', models.F('cultural_score')), output_field=models.IntegerField()),
        ),
    ]
