# Generated by Django 6.0.2 on 2026-04-08 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_total_score'),
        ('university_structure', '0003_staff_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-total_score'], name='students_st_total_s_db7aa3_idx'),
        ),
    ]
