# Generated by Django 6.0.2 on 2026-07-03 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_initial'),
        ('university_structure', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Если заполнено - студент архивирован: скрыт из текущего рейтинга/списков/дашборда, но запись, история баллов и файлы сохранены. Проставляется при импорте для статусов отчислен/окончил/архив или для студентов, пропавших из полной выгрузки.', null=True, verbose_name='В архиве с'),
        ),
        migrations.AlterField(
            model_name='student',
            name='external_id',
            field=models.CharField(blank=True, help_text='Код студента из БД вуза', max_length=50, null=True, unique=True, verbose_name='Код студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='university_structure.group'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['archived_at'], name='students_st_archive_7e1067_idx'),
        ),
    ]
